
CREATE DATABASE IF NOT EXISTS companydb;

USE companydb;

CREATE TABLE empleados (
    id INT(11) NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(45) DEFAULT NULL,
    apellido VARCHAR(45) DEFAULT NULL,
    email VARCHAR(45) DEFAULT NULL,
    telefono VARCHAR(45) DEFAULT NULL,
    salario INT(11) DEFAULT NULL,
    PRIMARY KEY (id)
);

DESCRIBE empleados;

